<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order) : ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items" style="width: 100%">
        <thead>
            <tr>
                <th align="left" bgcolor="#0098db"  class="item-info">
                    <?= $block->escapeHtml(__('Items')) ?>
                </th>
                <th align="left" bgcolor="#0098db"  class="item-qty">
                    <?= $block->escapeHtml(__('Sku')) ?>
                </th>
                <th align="right" bgcolor="#0098db"  class="item-qty">
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>
                <th align="right" bgcolor="#0098db"  class="item-price">
                    <?= $block->escapeHtml(__('Subtotal')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item) : ?>
            <?php if (!$_item->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->isMessagesAllowed('order', $_order, $_order->getStore())
        && $_order->getGiftMessageId()
    ) : ?>
        <?php $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage) : ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>


<style>

    .email-items{
        width: 100%;
        border: 1px solid #0098db;
        border-spacing: 0;
        border-collapse: collapse;
        font-size: 13px;
    }
    .email-items tbody{
        border: 1px dotted #999;
    }
    .email-items tr td.item-qty,
    .email-items tr td.item-price{
        text-align: right;
    }
    .email-items td{
        padding: 5px;
    }
    .email-items td p{
        margin: 0;
    }
    .email-items thead tr th{
        color: #fff;
        font-size: 13px;
        padding: 5px 9px 6px 9px;
        line-height: 1em;
        background-color: #0098db;
    }

    .email-items td dl{
        margin: 0 0 0 15px;
    }


</style>
