<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<div class="product-addto-links" data-role="add-to-links">
    <?= $block->getChildHtml() ?>
    <a href="#" class="action price-best">
    	<span><?= __("Price Beat") ?></span>
    </a>	
</div>
<script type="text/x-magento-init">
    {
	    "*": {
	        "Magento_Catalog/js/product/view/addto": {
	            "data": {}
	        }
	    }
	}
</script>