<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
if ($block->getMode() == 'grid') {
    $viewMode = 'grid';
    $imageDisplayArea = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
} else {
    $viewMode = 'list';
    $imageDisplayArea = 'category_page_list';
    $showDescription = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
}

$catalogHelper = $this->helper('Bss\CatalogHelper\Helper\Category');
$subcategories = $catalogHelper->getChildCategories();
?>




<?php if($subcategories): ?>
<div class="categories wrapper <?= /* @escapeNotVerified */ $viewMode ?> categories-<?= /* @escapeNotVerified */ $viewMode ?>">
    <ol class="categories list items category-items">
        <?php foreach ($subcategories as $category): ?>
        <li class="item category category-item">
            <a href="<?= $category->getUrl() ?>" class="category photo category-item-photo">
                <span class="category-image-wrapper">
                   <img src="<?= $catalogHelper->getCategory($category->getId())->getImageUrl() ?>" alt="<?= $category->getName(); ?>" class="product-image-photo">
                </span>
            </a>
            <div class="category details category-item-details">
                <span class="category name category-item-name">
                    <a href="<?= $category->getUrl(); ?>" class="category-item-link">
                        <?= $category->getName(); ?>
                    </a> 
                </span>
                <?php
                $limit = 50;
                    $_category = $catalogHelper->getCategory($category->getId());
                    $_description = $_category->getDescription();
                    $_description = substr($catalogHelper->truncateWords($_description,$limit),0,260) . "….";
                    if ($_description):
                ?>
                <div class="category-description">
                    <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($_category, $_description, 'description') ?>
                    <a href="<?= $category->getUrl(); ?>" class="view-categories">
                        <?= __("View products") ?>
                    </a>
                </div>
                <?php endif; ?>
            </div>
        </li>
        <?php endforeach; ?>
    </ol>
</div>

<?php else: ?>
    <?php
    $_productCollection = $block->getLoadedProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <?php if (!$_productCollection->count()): ?>
        <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
    <?php else: ?>
        <?= $block->getToolbarHtml() ?>
        <?= $block->getAdditionalHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $imageDisplayArea = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $imageDisplayArea = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                            <?php if ($block->getMode() == 'list'): ?>
                            <div class="product-item-sku">
                                <div class="product-sku">
                                    <span class="label"><?php echo __("Sku: ") ?></span>
                                    <span class="sku"><?php echo $_product->getSku(); ?></span>
                                </div>
                            </div>
                            <?php endif; ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                            <?= $block->getProductDetailsHtml($_product ) ?>
                            <?php if($_product->getAttributeText('free_shipping') && $_product->getAttributeText('free_shipping') != 'No Free Shipping'): ?>
                                <div class="free-shipping">
                                    <?php echo $_product->getAttributeText('free_shipping'); ?>
                                </div>
                            <?php endif; ?>
                            <?php
                            $attribute0 = $_product->getResource()->getAttribute('a01_specialorder_admin');
                            $attribute1 = $_product->getResource()->getAttribute('a01_backorder_admin');
                            $attribute2 = $_product->getResource()->getAttribute('a02_backorder_admin');
                            $attribute3 = $_product->getResource()->getAttribute('a03_backorder_admin');
                            $attribute4 = $_product->getResource()->getAttribute('a04_backorder_admin');
                            $attribute5 = $_product->getResource()->getAttribute('a05_backorder_admin');
                            $attribute6 = $_product->getResource()->getAttribute('pickup_only');
                            ?>
                            <?php if(($attribute6) &&  $attribute6->getFrontend()->getValue($_product) != 'No Pickup'): ?>
                                <div>
                                    <?php echo $attribute6->getFrontend()->getValue($_product); ?>
                                </div>
                            <?php endif; ?>

                            <?php if(($attribute0) &&  $attribute0->getFrontend()->getValue($_product) != 'No'): ?>
                                <div>
                                    <?php echo $attribute0->getFrontend()->getValue($_product); ?>
                                </div>
                            <?php endif; ?>

                            <?php if(($attribute1) &&  $attribute1->getFrontend()->getValue($_product) != 'No'): ?>
                                <div>
                                    <?php echo $attribute1->getFrontend()->getValue($_product); ?>
                                </div>
                            <?php endif; ?>
                            <?php if(($attribute2) &&  $attribute2->getFrontend()->getValue($_product) != 'No'): ?>
                                <div>
                                    <?php echo $attribute2->getFrontend()->getValue($_product); ?>
                                </div>
                            <?php endif; ?>
                            <?php if(($attribute3) &&  $attribute3->getFrontend()->getValue($_product) != 'No'): ?>
                                <div>
                                    <?php echo $attribute3->getFrontend()->getValue($_product); ?>
                                </div>
                            <?php endif; ?>
                            <?php if(($attribute4) &&  $attribute4->getFrontend()->getValue($_product) != 'No'): ?>
                                <div>
                                    <?php echo $attribute4->getFrontend()->getValue($_product); ?>
                                </div>
                            <?php endif; ?>
                            <?php if(($attribute5) &&  $attribute5->getFrontend()->getValue($_product) != 'No'): ?>
                                <div>
                                    <?php echo $attribute5->getFrontend()->getValue($_product); ?>
                                </div>
                            <?php endif; ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                           class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <div class="product-item-sku">
                                <div class="product-sku">
                                    <span class="label"><?php echo __("Sku: ") ?></span>
                                    <span class="sku"><?php echo $_product->getSku(); ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <?php endforeach; ?>
            </ol>
        </div>
        <?= $block->getToolbarHtml() ?>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                    }
                }
            }
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>