
<div class="block newsletter">
    <div class="title"><strong><?php /* @escapeNotVerified */ echo __('Newsletter Signup') ?></strong></div>
    <div class="content">
        <form class="form subscribe" novalidate
            action="<?php echo $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field firstname">
                <label class="label" for="firstname"><span><?php echo $block->escapeHtml(__('First Name')) ?></span></label>
                <div class="control">
                    <input name="firstname" type="text" id="firstname" placeholder="<?php echo $block->escapeHtml(__('Enter your first name')) ?>" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php echo $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter" placeholder="<?php echo $block->escapeHtml(__('Enter your email address')) ?>" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <?= $block->getChildHtml('webforms-recaptcha') ?>
            <div class="actions">
                <button class="action subscribe primary" title="<?php echo $block->escapeHtml(__('Subscribe')) ?>" type="submit">
                    <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>