<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Edit $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
	
		<a class="action edit" href="<?= $block->escapeUrl($block->getItemConfigureUrl($item)) ?>">
        	<button type="button" class="edit-item"><?= $block->escapeHtml(__('Edit')) ?></button>
    	</a>
	
    
<?php endif ?>
