<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <div class="product-item-sku">
                    <span class="type"><?= __("Sku") ?></span>
                    <span class="value"><?= $product->getSku() ?></span>
                </div>
                <?php if($product->getData('free_shipping') && $product->getAttributeText('free_shipping') != "No Free Shipping"): ?>
                    <div class="free-shipping">
                        <?= $product->getAttributeText('free_shipping') ?>
                    </div>
                <?php endif; ?>
                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());

                $attribute0 = $_product->getResource()->getAttribute('a01_specialorder_admin');
                $attribute1 = $_product->getResource()->getAttribute('a01_backorder_admin');
                $attribute2 = $_product->getResource()->getAttribute('a02_backorder_admin');
                $attribute3 = $_product->getResource()->getAttribute('a03_backorder_admin');
                $attribute4 = $_product->getResource()->getAttribute('a04_backorder_admin');
                $attribute5 = $_product->getResource()->getAttribute('a05_backorder_admin');
                $attribute6 = $_product->getResource()->getAttribute('pickup_only');
                ?>
                <?php if(($attribute6) &&  $attribute6->getFrontend()->getValue($_product) != 'No Pickup'): ?>
                    <div>
                        <?php echo $attribute6->getFrontend()->getValue($_product); ?>
                    </div>
                <?php endif; ?>

                <?php if(($attribute0) &&  $attribute0->getFrontend()->getValue($_product) != 'No'): ?>
                    <div>
                        <?php echo $attribute0->getFrontend()->getValue($_product); ?>
                    </div>
                <?php endif; ?>

                <?php if(($attribute1) &&  $attribute1->getFrontend()->getValue($_product) != 'No'): ?>
                    <div>
                        <?php echo $attribute1->getFrontend()->getValue($_product); ?>
                    </div>
                <?php endif; ?>
                <?php if(($attribute2) &&  $attribute2->getFrontend()->getValue($_product) != 'No'): ?>
                    <div>
                        <?php echo $attribute2->getFrontend()->getValue($_product); ?>
                    </div>
                <?php endif; ?>
                <?php if(($attribute3) &&  $attribute3->getFrontend()->getValue($_product) != 'No'): ?>
                    <div>
                        <?php echo $attribute3->getFrontend()->getValue($_product); ?>
                    </div>
                <?php endif; ?>
                <?php if(($attribute4) &&  $attribute4->getFrontend()->getValue($_product) != 'No'): ?>
                    <div>
                        <?php echo $attribute4->getFrontend()->getValue($_product); ?>
                    </div>
                <?php endif; ?>
                <?php if(($attribute5) &&  $attribute5->getFrontend()->getValue($_product) != 'No'): ?>
                    <div>
                        <?php echo $attribute5->getFrontend()->getValue($_product); ?>
                    </div>
                <?php endif; ?>
                <?php if ($_options = $block->getOptionList()):?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */ __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */ $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */ $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */ __("What's this?") ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <label class="label" for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                    <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
                </label>
                <div class="control qty">
                    <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                           name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                           value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                </div>
                <div class="control edit" data-product-id="<?= $_item->getId() ?>"><span><?= __("edit")  ?></span></div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
        <td class="col action remove" data-product-id="<?= $_item->getId() ?>">
            <span></span>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="4">
            <div class="actions-toolbar">
                <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>

