<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
        <th colspan="3" scope="row">
            <?php if ($_total->getStrong()) : ?>
                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else : ?>
                <?= $block->escapeHtml($_total->getLabel()) ?>
            <?php endif ?>
        </th>
        <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()) : ?>
                <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
            <?php else : ?>
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif; ?>
<?php endforeach?>


<style>
    tfoot.order-totals tr th,
    tfoot.order-totals tr td {
        text-align: right;
    }
    tfoot.order-totals tr th{
        font-weight: normal;
    }
    tfoot.order-totals tr.grand_total th{
        font-weight: bold;
    }
</style>
