<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Bss\OrderInfo\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <h2 class="sub-title">Thank you for your purchase!</h2>
            <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
        <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
        <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
            <p><?= __('Click %1 a copy of your order confirmation.', sprintf('<a href="%s">%s</a>', $block->escapeHtml($block->getPrintUrl()), 'here to print')) ?></p>
        <?php endif; ?>

    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <?= $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('addition_info_success_page')
            ->toHtml()
        ?>
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>



<?php
if ($block->getShippingMethod() == "flatrate_flatrate"){
    echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('customer_courier_message')
        ->toHtml();
}elseif($block->getShippingMethod() == "freeshipping_freeshipping"){
    echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('customer_pickup_message')
        ->toHtml();
}else{
    //An orther Shipping method !
}
?>

