
<?php $url= $block->getBaseUrl(); ?>
<div id="link-sitemap">
	<a href="<?= $url.'catalog/seo_sitemap/category' ?>" title="Pages Sitemap"><?= __("Categories Sitemap") ?></a><br>
	<a href="<?= $url.'catalog/seo_sitemap/product/' ?>" title="Products Sitemap"><?= __("Products Sitemap") ?></a>
</div>
<div id="mageplaza-seo-html-sitemap">
    <?php echo $block->renderHtmlSitemapPage(); ?>
</div>
<div id="link-sitemap">
	<a href="<?= $url.'catalog/seo_sitemap/category' ?>" title="Pages Sitemap"><?= __("Categories Sitemap") ?></a><br>
	<a href="<?= $url.'catalog/seo_sitemap/product/' ?>" title="Products Sitemap"><?= __("Products Sitemap") ?></a>
</div>

