<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$cataloghelper = $this->helper('Bss\CatalogHelper\Helper\Category');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$sku = $block->getSaleableItem()->getSku();
$priceModel = $block->getPriceType('regular_price');
$priceRRP = $block->getSaleableItem()->getData("price_rrp");
$regularPrice = $block->getPriceType('regular_price')->getAmount()->getValue();
$finalPrice = $cataloghelper->getSpecialPrice($sku);
/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if ($block->hasSpecialPrice() || $cataloghelper->hasSpecialPrice($sku)): ?>
    <?php if(!$block->hasSpecialPrice()): ?>
        <?php
            $specialPrice = $priceHelper->currency($cataloghelper->getSpecialPrice($sku), true, false);
        ?>
        <span class="special-price">
            <span class="price-container">
                <span class="price-label"><?= __("Special Price ") ?></span>
                <span 
                    id="product-price-<?= $idSuffix ?>" 
                    data-price-amount="<?= $specialPrice ?>"
                    data-price-type="finalPrice"
                    class="price-wrapper">
                    <span class="price"><?= $specialPrice ?></span>
                </span>
            </span>
        </span>
    <?php else: ?>
        <?php
            $regularPrice = $block->getPriceType('regular_price')->getAmount()->getValue();
            $finalPrice = $block->getPriceType('final_price')->getAmount()->getValue();
        ?>
        <span class="special-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
    <?php endif; ?>

    <?php if($priceRRP): ?>
        <span class="rrp-price">
            <span class="price-container">
                <span class="price-label"><?= __("RRP: ") ?></span>
                <span 
                    id="rrp-price-<?= $idSuffix ?>" 
                    data-price-amount="<?= $priceRRP ?>"
                    data-price-type="rrpPrice"
                    class="price-wrapper">
                    <span class="price"><?= $priceHelper->currency($priceRRP, true, false) ?></span>
                </span>
            </span>
        </span>
        <span class="save-price">
            <span class="price-container">
                <span class="price-label"><?= __("You Save: ") ?></span>
                <span 
                    id="save-price-<?= $idSuffix ?>" 
                    data-price-amount="<?= $priceRRP- $finalPrice ?>"
                    data-price-type="savePrice"
                    class="price-wrapper">
                    <span class="price"><?= $priceHelper->currency(($priceRRP - $finalPrice), true, false) ?></span>
                </span>
            </span>
        </span>
    <?php endif; ?>
    <span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php else: ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
    <?php if($priceRRP): ?>
        <span class="rrp-price">
            <span class="price-container">
                <span class="price-label"><?= __("RRP") ?></span>
                <span 
                    id="rrp-price-<?= $idSuffix ?>" 
                    data-price-amount="<?= $priceRRP ?>"
                    data-price-type="rrpPrice"
                    class="price-wrapper">
                    <span class="price"><?= $priceHelper->currency($priceRRP, true, false) ?></span>
                </span>
            </span>
        </span>
        <span class="save-price">
            <span class="price-container">
                <span class="price-label"><?= __("You Save: ") ?></span>
                <span 
                    id="save-price-<?= $idSuffix ?>" 
                    data-price-amount="<?= $priceRRP- $finalPrice ?>"
                    data-price-type="savePrice"
                    class="price-wrapper">
                    <span class="price"><?= $priceHelper->currency(($priceRRP - $finalPrice), true, false) ?></span>
                </span>
            </span>
        </span>
    <?php endif; ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
